# Generated by Django 4.1.2 on 2022-10-30 05:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('job_description', models.FileField(upload_to='job_description/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('no_of_seats', models.IntegerField()),
                ('stipend', models.IntegerField()),
                ('location', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=10)),
                ('experience_required', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposting_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isUser', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('contact_num', models.IntegerField(blank=True, null=True, verbose_name='Contact Number')),
                ('education', models.TextField()),
                ('experience_yrs', models.IntegerField(default=0)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('willing_to_work_at', models.CharField(max_length=40)),
                ('certificates', models.ManyToManyField(related_name='user_certificates', to='home.certificate')),
                ('skills', models.ManyToManyField(related_name='user_skills', to='home.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('companies', models.ManyToManyField(related_name='room_companies', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(to='home.message')),
                ('users', models.ManyToManyField(related_name='room_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobposting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jobposting')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='domain_tags',
            field=models.ManyToManyField(related_name='jobposting_domain_tags', to='home.tag'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirement_tags',
            field=models.ManyToManyField(related_name='jobposting_requirement_tags', to='home.tag'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='users_accepted',
            field=models.ManyToManyField(blank=True, related_name='users_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='willing_to_hire',
            field=models.ManyToManyField(blank=True, related_name='users_willing_to_hire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('company', models.ManyToManyField(related_name='feedback_company', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompany', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=40)),
                ('contact_num', models.IntegerField(blank=True, null=True, verbose_name='Contact Number')),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('jobpostings', models.ManyToManyField(blank=True, related_name='job_postings', to='home.jobposting')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
