# Generated by Django 4.1.2 on 2022-10-26 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='users_accepted',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='users_accepted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
