# Generated by Django 4.1.2 on 2022-10-30 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 5, 50, 54, 398533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 5, 50, 54, 402849, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 5, 50, 54, 401569, tzinfo=datetime.timezone.utc)),
        ),
    ]
