# Generated by Django 4.1.2 on 2022-10-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_message_time_alter_notification_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='website_link',
            field=models.CharField(default='www.google.com', max_length=40),
            preserve_default=False,
        ),
    ]
