# Generated by Django 4.1.2 on 2022-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_company_name_alter_jobposting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='jobpostings',
            field=models.ManyToManyField(blank=True, related_name='job_posting', to='home.jobposting'),
        ),
    ]
