# Generated by Django 4.1.2 on 2022-10-28 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_jobposting_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contact_num',
            field=models.IntegerField(default=1234567890, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Contact Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='number_of_employees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='domain_tags',
            field=models.ManyToManyField(related_name='jobposting_domain_tags', to='home.tag'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='experience_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='no_of_seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='position',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirement_tags',
            field=models.ManyToManyField(related_name='jobposting_requirement_tags', to='home.tag'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='stipend',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_num',
            field=models.IntegerField(default=1234567890, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Contact Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_yrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='willing_to_work_at',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
