# Generated by Django 4.1.2 on 2022-10-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_notification_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.feedback'),
        ),
    ]
