# Generated by Django 4.1.2 on 2022-10-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_feedback_company_remove_feedback_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_num',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_num',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
    ]
