# Generated by Django 4.1.2 on 2022-10-29 18:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_companyprofile_contact_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='willing_to_hire',
            field=models.ManyToManyField(blank=True, related_name='users_willing_to_hire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_description',
            field=models.FileField(upload_to='job_description/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
