# Generated by Django 4.1.2 on 2022-10-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_jobposting_willing_to_hire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='jobposting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.jobposting'),
            preserve_default=False,
        ),
    ]
