# Generated by Django 4.1.2 on 2022-10-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_notification_jobposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
    ]
